name: Prerelease

on:
  push:
    branches:
      - next

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.0

      - name: Add auth token to .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:libs

      # Are we already in pre mode?
      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".changeset/pre.json"

      # If .changeset/pre.json does not exist and we did not recently exit
      # prerelease mode, enter prerelease mode with tag next
      - name: Enter next prerelease mode
        if: steps.check_files.outputs.files_exists == 'false' && !contains(github.event.head_commit.message, 'Exit prerelease')
        run: npx changeset pre enter next

      - name: Create next release PR
        id: changesets-pr
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "Create prerelease"
          title: "Create prerelease"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run publish prerelease
        id: changesets-publish
        # Only run publish if we're still in pre mode and the last commit was
        # via an automatically created Version Packages PR
        if: steps.check_files.outputs.files_exists == 'true' && startsWith(github.event.head_commit.message, 'Create prerelease')
        run: npm run changeset-publish
